### ISSUE TITLE
Does not work with scribe > 1.4.x

### ISSUE THREAD

**Issue by hamnis** [guardian/scribe-plugin-curly-quotes#25]
Problem with lodash-amd which has moved the `toArray` to `lang` from `collections`

**Comment by hmgibson23** [comment]
Okay. Should be a pretty trivial one to correct.

**Comment by rrees** [comment]
Okay v1.0.0 should have fixed this now. @hamnis can you check on your system?

**Comment by hamnis** [comment]
This does not work correctly. In the meantime lodash has deprecated lodash-amd, so i suggest creating a toArray for this particular purpose. Will add a PR for this shortly.

**Comment by rrees** [comment]
Okay, I'll try and keep an eye out for the PR

**Comment by hamnis** [comment]
PR #31 fixes this.

The tests are failing, but I think they are failing in master as well. If master is fixed, i will rebase and re-push.
